# Generated by Django 4.0.4 on 2022-04-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='base.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='base.producttype'),
        ),
    ]
