# Generated by Django 4.0.4 on 2022-04-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_product_color_id_alter_product_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_id',
        ),
        migrations.AddField(
            model_name='color',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
            preserve_default=False,
        ),
    ]
