# Generated by Django 4.0.4 on 2022-04-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_product_color_id_remove_product_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='base.category'),
        ),
        migrations.AlterField(
            model_name='color',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='base.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.product'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='base.product'),
        ),
    ]
