# Generated by Django 3.2.6 on 2022-04-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220419_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link_to',
            field=models.CharField(default='', max_length=100),
        ),
    ]
