# Generated by Django 4.0.4 on 2022-04-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
