# Generated by Django 4.0.4 on 2022-04-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_images_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
