# Generated by Django 4.0.4 on 2022-04-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_orderitem_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery',
            new_name='delivery_choice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
