# Generated by Django 4.0.4 on 2022-04-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_uuid',
            field=models.CharField(default='O2022230411', max_length=6),
        ),
    ]
