# Generated by Django 4.0.4 on 2022-04-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_order_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_uuid',
            field=models.CharField(default='O2022230411', max_length=15),
        ),
    ]
