export const sliderItems = [
    {
      id: 1,
      img: "https://clipart.info/images/ccovers/1496091499Furniture-PNG-Picture-oriental.png",
      title: "SUMMER SALE",
      desc: "DON'T COMPROMISE ON LUXURY! GET FLAT 30% OFF FOR NEW ARRIVALS.",
      bg: "f5fafd",
    },
    {
      id: 2,
      img: "https://res.cloudinary.com/brosa-design/image/fetch/c_fill,dpr_1.0,f_auto,h_630,q_auto:good,w_1125/https://s3-ap-southeast-2.amazonaws.com/brosadesign.com/products/3744/original/french%2520beige/cristoph-3-seater-sofa-french-beige-1.png",
      title: "AUTUMN COLLECTION",
      desc: "LIVE YOUR LIFE WITH A DELUXE FURNITURES FROM US.",
      bg: "fcf1ed",
    },
    {
      id: 3,
      img: "https://cdn.livingstyles.com.au/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/T/T/TTAPAS.jpg",
      title: "LOUNGEWEAR LOVE",
      desc: "GOT YOUR FAMILY? WE GOT YOU COVERD. JUST SHOP AND GET IT DELIVERED AT HOME.",
      bg: "fbf0f4",
    },
    {
      id: 4,
      img: "https://cdn.livingstyles.com.au/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/T/T/TTAPAS.jpg",
      title: "LOUNGEWEAR LOVE",
      desc: "GOT YOUR FAMILY? WE GOT YOU COVERD. JUST SHOP AND GET IT DELIVERED AT HOME.",
      bg: "fbf0f4",
    },
  ];

  export const categories = [
    {
      id: 1,
      img: "https://clipart.info/images/ccovers/1496091499Furniture-PNG-Picture-oriental.png",
      title: "FAMILY VACATION",
      desc: "DON'T COMPROMISE ON LUXURY! GET FLAT 30% OFF FOR NEW ARRIVALS.",
      bg: "f5fafd",
    },
    {
      id: 2,
      img: "https://res.cloudinary.com/brosa-design/image/fetch/c_fill,dpr_1.0,f_auto,h_630,q_auto:good,w_1125/https://s3-ap-southeast-2.amazonaws.com/brosadesign.com/products/3744/original/french%2520beige/cristoph-3-seater-sofa-french-beige-1.png",
      title: "LUXURY COLLECTION",
      desc: "LIVE YOUR LIFE WITH A DELUXE FURNITURES FROM US.",
      bg: "fcf1ed",
    },
    {
      id: 3,
      img: "https://cdn.livingstyles.com.au/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/T/T/TTAPAS.jpg",
      title: "SWEET HOME",
      desc: "GOT YOUR FAMILY? WE GOT YOU COVERD. JUST SHOP AND GET IT DELIVERED AT HOME.",
      bg: "fbf0f4",
    },
    {
      id: 4,
      img: "https://clipart.info/images/ccovers/1496091499Furniture-PNG-Picture-oriental.png",
      title: "FAMILY VACATION",
      desc: "DON'T COMPROMISE ON LUXURY! GET FLAT 30% OFF FOR NEW ARRIVALS.",
      bg: "f5fafd",
    },
    {
      id: 5,
      img: "https://res.cloudinary.com/brosa-design/image/fetch/c_fill,dpr_1.0,f_auto,h_630,q_auto:good,w_1125/https://s3-ap-southeast-2.amazonaws.com/brosadesign.com/products/3744/original/french%2520beige/cristoph-3-seater-sofa-french-beige-1.png",
      title: "LUXURY COLLECTION",
      desc: "LIVE YOUR LIFE WITH A DELUXE FURNITURES FROM US.",
      bg: "fcf1ed",
    },
    {
      id:6,
      img: "https://cdn.livingstyles.com.au/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/T/T/TTAPAS.jpg",
      title: "SWEET HOME",
      desc: "GOT YOUR FAMILY? WE GOT YOU COVERD. JUST SHOP AND GET IT DELIVERED AT HOME.",
      bg: "fbf0f4",
    },
    {
      id: 7,
      img: "https://clipart.info/images/ccovers/1496091499Furniture-PNG-Picture-oriental.png",
      title: "FAMILY VACATION",
      desc: "DON'T COMPROMISE ON LUXURY! GET FLAT 30% OFF FOR NEW ARRIVALS.",
      bg: "f5fafd",
    },
    {
      id: 8,
      img: "https://res.cloudinary.com/brosa-design/image/fetch/c_fill,dpr_1.0,f_auto,h_630,q_auto:good,w_1125/https://s3-ap-southeast-2.amazonaws.com/brosadesign.com/products/3744/original/french%2520beige/cristoph-3-seater-sofa-french-beige-1.png",
      title: "LUXURY COLLECTION",
      desc: "LIVE YOUR LIFE WITH A DELUXE FURNITURES FROM US.",
      bg: "fcf1ed",
    },
    {
      id:9,
      img: "https://cdn.livingstyles.com.au/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/T/T/TTAPAS.jpg",
      title: "SWEET HOME",
      desc: "GOT YOUR FAMILY? WE GOT YOU COVERD. JUST SHOP AND GET IT DELIVERED AT HOME.",
      bg: "fbf0f4",
    },
  ];

  export const popularProducts = [
    {
      id:1,
      title:"Dresden Sectional Sofa",
      img:"https://res.cloudinary.com/brosa-design/image/fetch/c_fill,dpr_1.0,f_auto,h_630,q_auto:good,w_1125/https://s3-ap-southeast-2.amazonaws.com/brosadesign.com/products/3744/original/french%2520beige/cristoph-3-seater-sofa-french-beige-1.png",
      price:759,
      rating:4.5,
      ratingsCount:10,
    },
    {
      id:2,
      title:"Tapas Rubberwood Timber Extension Dining Table (Table Only), 105-135cm",
      img:"https://cdn.livingstyles.com.au/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/T/T/TTAPAS.jpg",
      price:224.10,
      rating:3.8,
      ratingsCount:5,
    },
    {
      id:3,
      title:"OVALIS Dining Table Petite Washed Natural",
      img:"https://i1.wp.com/www.lamaison.net.au/wp-content/uploads/2019/04/timthumb-1-2.png",
      price:1699,
      rating:5,
      ratingsCount:4,
    },
    {
      id:4,
      title:"Dresden Sectional Sofa",
      img:"https://res.cloudinary.com/brosa-design/image/fetch/c_fill,dpr_1.0,f_auto,h_630,q_auto:good,w_1125/https://s3-ap-southeast-2.amazonaws.com/brosadesign.com/products/3744/original/french%2520beige/cristoph-3-seater-sofa-french-beige-1.png",
      price:759,
      rating:4.1,
      ratingsCount:2,
    },
    {
      id:5,
      title:"Dresden Sectional Sofa",
      img:"https://res.cloudinary.com/brosa-design/image/fetch/c_fill,dpr_1.0,f_auto,h_630,q_auto:good,w_1125/https://s3-ap-southeast-2.amazonaws.com/brosadesign.com/products/3744/original/french%2520beige/cristoph-3-seater-sofa-french-beige-1.png",
      price:759,
      rating:4.5,
      ratingsCount:10,
    },
    {
      id:6,
      title:"Tapas Rubberwood Timber Extension Dining Table (Table Only), 105-135cm",
      img:"https://cdn.livingstyles.com.au/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/T/T/TTAPAS.jpg",
      price:224.10,
      rating:3.8,
      ratingsCount:5,
    },
    {
      id:7,
      title:"OVALIS Dining Table Petite Washed Natural",
      img:"https://i1.wp.com/www.lamaison.net.au/wp-content/uploads/2019/04/timthumb-1-2.png",
      price:1699,
      rating:5,
      ratingsCount:4,
    },
    {
      id:8,
      title:"Dresden Sectional Sofa",
      img:"https://res.cloudinary.com/brosa-design/image/fetch/c_fill,dpr_1.0,f_auto,h_630,q_auto:good,w_1125/https://s3-ap-southeast-2.amazonaws.com/brosadesign.com/products/3744/original/french%2520beige/cristoph-3-seater-sofa-french-beige-1.png",
      price:759,
      rating:4.1,
      ratingsCount:2,
    },
    
  ]